name: recycle_hub
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
version: 1.0.3+5

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  rxdart: ^0.27.0
  dio: ^4.0.0
  eva_icons_flutter: ^3.0.0
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.5
  google_maps_flutter: ^2.0.5
  http: ^0.13.3
  permission_handler: ^8.0.0+1
  bottom_sheet: ^1.0.1
  auto_size_text: ^2.1.0
  snapping_sheet: ^3.1.0
  font_awesome_flutter: ^9.0.0
  flutter_star_rating: ^0.0.3
  location: ^4.1.1
  cached_network_image: ^3.0.0
  intl: ^0.17.0
  flutter_typeahead: ^3.1.3
  flutter_svg: ^0.22.0
  day_night_switcher: ^0.2.0+1
  im_stepper: ^0.1.3
  flutter_svg_provider: ^0.1.9
  flutter_screenutil: ^5.0.0+2
  mask_text_input_formatter: ^1.2.1
  #qr_code_scanner:
  #device_preview: ^0.6.2-beta
  google_maps_cluster_manager: ^1.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  menu_button: ^1.4.1
  step_progress_indicator: ^0.2.5+8
  url_launcher: ^6.0.4
  image_picker: ^0.7.5+2
  steps_indicator: ^1.3.0
  provider: ^5.0.0
  flutter_sequence_animation: ^3.0.1
  flutter_bloc: ^7.0.0
  flutter_secure_storage: ^4.2.0
  equatable: ^2.0.2
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0
  get_it: ^6.1.0
  flutter_easyrefresh: ^2.2.1 
  blur: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3


flutter:
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/icons/onboarding_1/People.svg


    - assets/icons/onboarding_1/Clouds.svg
    - assets/icons/onboarding_2/People.svg
    - assets/icons/onboarding_2/People.png

    - assets/icons/onboarding_3/People.svg
    - assets/icons/onboarding_4/People.svg
    - assets/icons/socials/vk.svg
    - assets/icons/socials/fb.svg
    - assets/icons/socials/in.svg
    - assets/icons/socials/telegram.png


    - assets/svg/background.svg
    - assets/svg/logo_original.svg
    - assets/svg/logo_original.png
    - assets/icons/reg/reg_logo.svg
    - svg/
    - assets/onboarding/back.png
    - assets/icons/files-transit.svg
    - assets/icons/files-transit.svg

  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/gilroy-regular.ttf
        - asset: assets/fonts/Gilroy/gilroy-bold.ttf
        - asset: assets/fonts/gilroy-medium.ttf
          style: normal
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy/gilroy-medium.ttf
          weight: 400
    - family: EcoCoinIcons
      fonts:
        - asset: assets/fonts/EcoCoinIcons.ttf

    - family: EcoGuideIcons
      fonts:
        - asset: assets/fonts/EcoGuideIcons.ttf

    - family: HowToGetCoinIcons
      fonts:
        - asset: assets/fonts/HowToGetCoinIcons.ttf

    - family: MenuIcons
      fonts:
        - asset: assets/fonts/MenuIcons.ttf

    - family: MyPyrchaseIcons
      fonts:
        - asset: assets/fonts/MyPyrchaseIcons.ttf

    - family: NavBarIcons
      fonts:
        - asset: assets/fonts/NavBarIcons.ttf

    - family: PPProfileIcons
      fonts:
        - asset: assets/fonts/PPProfileIcons.ttf

    - family: UserProfileIcons
      fonts:
        - asset: assets/fonts/UserProfileIcons.ttf

    - family: LofOut
      fonts:
        - asset: assets/fonts/LofOut.ttf
        
    - family: AppBarIcons
      fonts:
        - asset: assets/fonts/AppBarIcons.ttf

    