name: recycle_hub
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  rxdart: ^0.24.1
  dio: ^3.0.10
  eva_icons_flutter: ^2.0.1
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.12+2
  google_maps_flutter: ^1.0.6
  http: ^0.12.2
  permission_handler: ^5.0.1+1
  bottom_sheet: ^0.0.1-dev.7
  auto_size_text: ^2.1.0
  snapping_sheet: ^2.0.2
  font_awesome_flutter: ^8.11.0
  flutter_star_rating: ^0.0.3
  location: ^3.2.4
  cached_network_image: ^2.5.0
  intl: ^0.16.1
  flutter_typeahead: ^2.0.0
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  assets:
    - assets/
    - assets/fonts/

  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/gilroy-regular.ttf
        - asset: assets/fonts/Gilroy/gilroy-bold.ttf
          style: normal
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy/gilroy-medium.ttf
          weight: 400
    - family: LofOut
      fonts:
        - asset: assets/fonts/LofOut.ttf