name: recycle_hub
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.9.0-13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  rxdart: ^0.25.0
  dio: ^3.0.8
  eva_icons_flutter: ^2.0.1
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.12+4
  google_maps_flutter: ^1.2.0
  http: ^0.12.2
  permission_handler: ^5.1.0+2
  bottom_sheet: ^0.0.1-dev.7
  auto_size_text: ^2.1.0
  snapping_sheet: ^2.0.2
  font_awesome_flutter: ^8.11.0
  flutter_star_rating: ^0.0.3
  location: ^3.2.4
  cached_network_image: ^2.4.1
  intl: ^0.16.1
  flutter_typeahead: ^2.0.0
  flutter_svg: ^0.19.2+1
  day_night_switcher: ^0.1.1+1
  draggable_bottom_sheet: ^0.1.2
  im_stepper: 0.1.2+10
  flutter_svg_provider: ^0.1.8
  flutter_screenutil: ^4.0.3+2
  mask_text_input_formatter: ^1.2.1
  qr_code_scanner:
  #device_preview: ^0.6.2-beta
  google_maps_cluster_manager: ^0.3.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.11.5


flutter:
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/icons/onboarding_1/People.svg
    - assets/icons/onboarding_1/Clouds.svg
    - assets/icons/onboarding_2/People.svg
    - assets/icons/onboarding_2/Clouds.svg
    - assets/icons/onboarding_3/People.svg
    - assets/icons/onboarding_3/Clouds.svg
    - assets/icons/onboarding_4/People.svg
    - assets/icons/onboarding_4/Clouds.svg
    - assets/svg/
    - svg/
    - assets/icons/reg/reg_logo.svg

  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/gilroy-regular.ttf
        - asset: assets/fonts/Gilroy/gilroy-bold.ttf
        - asset: fonts/gilroy-medium.ttf
          style: normal
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy/gilroy-medium.ttf
          weight: 400
    - family: LofOut
      fonts:
        - asset: assets/fonts/LofOut.ttf
    - family: TabIcons
      fonts:
        - asset: assets/fonts/TabIcons.ttf