/// Flutter icons EcoCoinIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EcoCoinIcons
///      fonts:
///       - asset: fonts/EcoCoinIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EcoCoinIcons {
  EcoCoinIcons._();

  static const _kFontFam = 'EcoCoinIcons';
  static const String _kFontPkg = null;

  static const IconData addpointer = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adduser = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recyclebin = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reviews = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoppingcart = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
