/// Flutter icons EcoGuideIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EcoGuideIcons
///      fonts:
///       - asset: fonts/EcoGuideIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EcoGuideIcons {
  EcoGuideIcons._();

  static const _kFontFam = 'EcoGuideIcons';
  static const String _kFontPkg = null;

  static const IconData book = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brain = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recyclebin = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
