/// Flutter icons HowToGetCoinIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HowToGetCoinIcons
///      fonts:
///       - asset: fonts/HowToGetCoinIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HowToGetCoinIcons {
  HowToGetCoinIcons._();

  static const _kFontFam = 'HowToGetCoinIcons';
  static const String _kFontPkg = null;

  static const IconData add_pointer = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_user = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brain = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reviews = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
