/// Flutter icons MenuIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MenuIcons
///      fonts:
///       - asset: fonts/MenuIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MenuIcons {
  MenuIcons._();

  static const _kFontFam = 'MenuIcons';
  static const String _kFontPkg = null;

  static const IconData contact = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedback = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instruction = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reviews = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
