/// Flutter icons PPProfileIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PPProfileIcons
///      fonts:
///       - asset: fonts/PPProfileIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PPProfileIcons {
  PPProfileIcons._();

  static const _kFontFam = 'PPProfileIcons';
  static const String _kFontPkg = null;

  static const IconData achievement = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData piechart = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoppingcart = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
