/// Flutter icons UserProfileIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UserProfileIcons
///      fonts:
///       - asset: fonts/UserProfileIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UserProfileIcons {
  UserProfileIcons._();

  static const _kFontFam = 'UserProfileIcons';
  static const String _kFontPkg = null;

  static const IconData achievement = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ask = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_payment = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
