/// Flutter icons TabIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TabIcons
///      fonts:
///       - asset: fonts/TabIcons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class TabIcons {
  TabIcons._();

  static const _kFontFam = 'TabIcons';
  static const String _kFontPkg = null;

  static const IconData guide_book =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_plus =
      IconData(0xf2b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
